name: isyumi_deltist
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: riku <riku@tanide.net>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  rocksdb_interop:
    path: /home/riku/WebstormProjects/rocksdb_interop
  crypto: ^2.1.1+1
  quiver: ^2.0.5

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
